name: Build and test
on: push
jobs:
  lint:
    name: Lint with Black
    runs-on: ubuntu-latest
    steps:
      - uses: "lgeiger/black-action@master"
        with:
          args: ". --check"
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: ${{ matrix.python-version }}
          poetry_version: 1.1.8
          args: install
      - name: Run pytest
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: ${{ matrix.python-version }}
          poetry_version: 1.1.8
          args: run python -m pytest