name: Publish to PyPi
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Build and publish to JFROG
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v1.9
      with:
        python_version: 3.8
        repository_name: artifactory
        repository_url: ${{ secrets.JFROG_PYPI_URL }}
        repository_username: ${{ secrets.JFROG_PYPI_USERNAME }}
        repository_password: ${{ secrets.JFROG_PYPI_PASS }}
  publish-pypi:
    name: Build and publish to PyPi
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v1.9
      with:
         pypi_token: ${{ secrets.PYPI_TOKEN }}
